# M10 Exercises

## Exercise 10.1

```{r}
x <- c(0,1)

for (y in  2:9) {
x <- c(x, x[y] + x[y-1])
}

x
```

## Exercise 10.2

```{r}
fibonnaci <- function(length) {
  x <- c(0,1)
  
  for (y in 2:length-1) {
    x <- c(x, x[y] + x[y-1])
  }
  return(x)
}

fibonnaci(15)
```

## Exercise 10.3

```{r}
between_0_and_1 <- function(x) {
  if (0 <= x & x <= 1) {
    return(1)
  }
  return(0)
}

between_0_and_1(0.4)
between_0_and_1(2)
```

## Exercise 10.4

```{r}
nums <- c(0.2,2,0.56,1.1,1)
for (i in 1:5){
  print(between_0_and_1(nums[i]))
}
```
## Exercise 10.5

```{r}
letters[1:10] # head(letters,10)
tail(LETTERS,10)
LETTERS[22:24]
```

## Exercise 10.6

```{r}

for(i in 1:100){
  
  if(i %% 3 == 0 & i %% 5 != 0) {
    print(paste(i,"Fizz"))
  }
  else if(i %% 3 != 0 & i %% 5 == 0) {
    print(paste(i,"Buzz"))
  }
  else if(i %% 3 == 0 & i %% 5 == 0) {
    print(paste(i,"FizzBuzz"))
  }
  else {
    print(paste(i))
  }
  
}
```

## Exercise 10.7

```{r}
vec <- c(10,10,4,5,6,7,7)

unique(vec)
```

## Exercise 10.8

```{r}
vec <- c(1,2,5,11,16)

print(paste("max:",max(vec),"min:",min(vec)))
```

## Exercise 10.9

```{r}
seq(20,50,1)
mean(20:50)
sum(51:91)
```

## Exercise 10.10

```{r}
df <- data.frame(
  c = c("data","frame","r","l","a","r","a","s","l","p"),
  f = c(1.1,2.3,3.4,4.5,5.5,6.5,7.5,8.3,9.2,10.1),
  i = c(1:10),
  b = c(T,F,T,F,F,F,T,F,T,F)
)

df
```

## Exercise 10.11

```{r}
airquality[c(3,5),c(1,3)]
```

## Exercise 10.12

```{r}
plot(mtcars[,c("hp","cyl","mpg")])
```
