# M12 Exercises

```{r}
library(vctrs)
library(tidyverse)
```

```{r}
head(mpg)
```

## Exercise 12.1

```{r}
mpg %>% 
  ggplot()
```

## Exercise 12.2

```{r}
mpg %>% 
  ggplot(aes(
    x = cyl, 
    y = hwy)) + 
  geom_point()
```

## Exercise 12.3

```{r}
mpg %>% 
  ggplot(aes(
    x = class, 
    y = drv)) + 
  geom_point()
```

## Exercise 12.4

```{r}

x <- seq(-6 * pi, 6 * pi, length.out = 100)

x <- data.frame(x)

x %>% 
  ggplot(aes(
    x = x,
    y = sin(x) / x
  )) +
  geom_line()

```

## Exercise 12.5

```{r}
cars %>% 
  ggplot(aes(
    x = speed,
    y = dist
  )) +
  geom_point()
```

## Exercise 12.6

```{r}
cars %>% 
  ggplot(
    aes(
      x = speed,
      y = dist, 
      color = dist > 80
      )
    ) +
  geom_point()
```

## Exercise 12.7

```{r}
cars %>% 
  ggplot(
    aes(
      x = speed,
      y = dist, 
      color = dist > 80
      )
    ) +
  geom_point() +
  scale_color_manual(
    name = "Distance > 80",
    values = c(
      "TRUE" = "red",
      "FALSE" = "blue"
    )
  )
```

## Exercise 12.8

```{r}
cars %>% 
  ggplot(
    aes(
      x = speed,
      y = dist
      )
    ) +
  geom_point(
    aes(
      color = dist > 80
      )
    ) +
  geom_smooth(method = "lm") +
  scale_color_manual(
    name = "Distance > 80",
    values = c(
      "TRUE" = "red",
      "FALSE" = "blue"
    )
  )
```

## Exercise 12.9

```{r}
cars %>% 
  ggplot(
    aes(
      x = speed,
      )
    ) +
  geom_histogram(bins = 10)
```

```{r}
cars %>% 
  ggplot(
    aes(
      x = dist
      )
    ) +
  geom_histogram(bins = 10)
```

## Exercise 12.10

```{r}
mpg %>% 
  ggplot () +
  geom_point(
    aes(
      x = hwy,
      y = cty
      )
    ) +
  facet_grid(drv ~ cyl)
```

## Exercise 12.11

```{r}
iris %>% 
  ggplot(aes(x=Sepal.Length, y=Sepal.Width, color=Species, shape=Species)) +
  geom_point() +
  geom_density2d() +
  ggtitle("IRIS") +
  theme_light()
```